// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwzeavggrkxokfmxddvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3emVhdmdncmt4b2tmbXhkZHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTc4ODIsImV4cCI6MjA3MjQzMzg4Mn0.ITshzRmzaO_gXRZNfJS6YUj0UcXi4Du43SgcUhMsMSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});